In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

arr = np.arange(100,105)
arr.dtype

arr_range = range(100,105)
type(arr_range)

range

In [16]:
data2 = [[1,2,3],[4,5,6]]

arr2 = np.array(data2)
type(arr2)
arr2.shape
arr2.ndim
arr_1 = np.ones(10)
arr3 = [1,2,3,4,5,6,7,8,9,11]
arr_ar = np.array(arr3)
arr_1 + arr_ar
arr_2 = np.arange(10)
arr_2 + arr_ar


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [19]:
arr = np.array([1,2,3,4,5])
arr_float = arr.astype(np.float64)
arr_float, arr_float.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [23]:
arr = np.arange(10)

arr_slice = arr[5:8]
arr_slice[:] = 10
arr_slice, arr


(array([10, 10, 10]), array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9]))

In [28]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0], arr2d[1],arr2d[2],arr2d[0:2],arr2d[0:3],arr2d[:],arr2d[0:],arr2d[0:10]


(array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [30]:
arr2d[0][1],arr2d[0,1],arr2d[0][1:]

(2, 2, array([2, 3]))

In [38]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr3d, arr3d[0], arr3d[1],arr3d[0][0],arr3d[0,0], arr3d[0][1],arr3d[0,1], sep='\n\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[1 2 3]

[1 2 3]

[4 5 6]

[4 5 6]


In [39]:
old = arr3d[0].copy()
arr3d[0] = 100
arr3d


array([[[100, 100, 100],
        [100, 100, 100]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])